package dfl.display;

/**
 * Keep the DfAnimations and DfSpritesheet objects data.
 * @author rogersanctus
 */
class DfContentDef
{
	public var animations: DfAnimations;
	public var spritesheet: DfSpritesheet;

	/**
	 * The content definitions
	 * @param	?animations		The animations object. It don't need to be passed.
	 * @param	spritesheet		The spritesheet object. If a animations object is passed,
	 * 							this param don't need to be passed as it will be generated by
	 * 							the DfAnimations class.
	 */
	public function new( ?animations: DfAnimations = null, spritesheet: DfSpritesheet = null )
	{
		this.animations = animations;
		this.spritesheet = spritesheet;
		
		if ( animations != null )
		{
			this.spritesheet = animations.spritesheet;
		}		
	}
	
}